# Configuration file for NexsSigns.
# Coded with love by thmihnea.

sign-format:
  - "&6SkyPvP"
  - "&6{amount}&ex &6{itemName}"
  - ""
  - "&7&o(( Click ))"
cooldown-message: "&cYou can't access this sign yet! {timeLeft} left before becoming re-accessible."